### ISSUE TITLE
Paper can view？

### ISSUE THREAD

**Issue by deliaiz** [sakibreza/ECCV24-HAT#1]
Now,only view Code.The paper can not be searched.Can you provide Paper？

**Comment by sakibreza** [comment]
Hi @deliaiz, Thanks for reaching out. I just uploaded the paper preprint - [link](https://github.com/sakibreza/ECCV24-HAT/blob/main/paper_preprint.pdf). It will also be available on Arxiv soon and later in the ECCV proceeding.

**Comment by deliaiz** [comment]
Thank you very much!




刘方瑾
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sakibreza/ECCV24-HAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月27日(星期六) 上午9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sakibreza/ECCV24-HAT] Paper can view？ (Issue #1)





 
Hi @deliaiz, Thanks for reaching out. I just uploaded the paper preprint - link. It will also be available on Arxiv soon and later in the ECCV proceeding.

**Comment by sakibreza** [comment]
@deliaiz  No worries at all! Please let me know if you need any other support. If you find this repository and my response helpful, please feel free to star ⭐ the repo. Thanks!
