### ISSUE TITLE
Request for  EGTEA dataset and pre-trained feature

### ISSUE THREAD

**Issue by szulmh** [sakibreza/ECCV24-HAT#2]
We found that the links of EGTEA and pre-trained feature could not be opened. May I ask when can you send the links of these two.

**Comment by sakibreza** [comment]
Hi @szulmh, I've added the link to the pre-extracted features of EGTEA in the **README** file. If you'd like to download the raw videos, you can use this link: [raw video links](https://www.dropbox.com/s/uwwj6wb1j4rsm02/video_links.txt?dl=0). Please let me know if you need any further support. If you find this repository and my response helpful, please feel free to star ⭐ the repo. Thanks!
