### ISSUE TITLE
Request for Pre-extracted EGTEA Features and Additional Dataset Configuration Files

### ISSUE THREAD

**Issue by maojiaqi2324** [sakibreza/ECCV24-HAT#3]
Hi Sakib Reza,

First of all, I would like to extend my sincere thanks for your outstanding work on this project. The tools and resources you've provided have been incredibly valuable, and your contributions to the community are greatly appreciated.

I wanted to ask if it would be possible for you to open-source the pre-extracted features of the EGTEA dataset? Having access to these would be extremely helpful for those of us looking to dive deeper into your work without the initial overhead of feature extraction.

Additionally, I was wondering if you have any plans to open-source configuration files or settings for other datasets? This would be immensely beneficial in helping others replicate your results and adapt your methods to different datasets.

Thank you again for your fantastic work and for considering this request. I look forward to your response.

Best regards,  
Matt

**Comment by sakibreza** [comment]
Hi @maojiaqi2324, Thanks for your kind words! I've added the links to the pre-extracted features of EGTEA and config files of the other datasets in the **README** file. Please let me know if you need any further support. If you find this repository and my response helpful, please feel free to star ⭐ the repo. Thanks!
